version: "3"
services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: ludy2014
      POSTGRES_USER: decio
      POSTGRES_DB: workout
    ports:
      - "5432:5432"